### ISSUE TITLE
create functions for code blocks

### ISSUE THREAD

**Issue by riccardoklinger** [riccardoklinger/OSMquery#12]
As users from reddit suggested, it would be better to create multiple functions for different parts of the script to support unit testing.

**Comment by rastrau** [comment]
Is there a discussion that you can link to?

**Comment by riccardoklinger** [comment]
![grafik](https://user-images.githubusercontent.com/7377897/44901216-0bd9ce80-ad07-11e8-8ba8-66c34fc2c213.png)
from Reddit/r/gis

**Comment by rastrau** [comment]
This has been addressed in various commits. There is more potential left for modularizing the code, but I'm closing this issue for now.
