### ISSUE TITLE
Change default for spatial extent to "Define simple extent"

### ISSUE THREAD

**Issue by rastrau** [riccardoklinger/OSMquery#14]
While the geocoding of toponyms is a nice feature, I suspect in most usage scenarios input spatial extent is specified using the map canvas or another layer present in the project. I would thus suggest switching the default from Geocoding to Simple Extent.

What do you think @riccardoklinger?

**Comment by riccardoklinger** [comment]
fixed in commit 8af285efd40b773136d91d40a17c7883287a63f3 .
Yet this might be reopened if we get other responses from the community.
