### ISSUE TITLE
date format in different regions leads to errors

### ISSUE THREAD

**Issue by riccardoklinger** [riccardoklinger/OSMquery#25]
A gis developer described the following issue: 
probably its because of time format that used in my laptop. this tools working perfectly when I changed date format in param7. 

original time format from your script.
param7.value = now.strftime("%d.%m.%Y %H:%M:%S")
modified time format.
param7.value = now.strftime("%d/%m/%Y %H:%M:%S")

**Comment by riccardoklinger** [comment]
@geoholix this is the issue

**Comment by geoholix** [comment]
I confirmed, this issue has been resolved. thank you

**Comment by scw** [comment]
You should be able to pass in the datetime around directly, and let the final `strftime` call in the execute use that instead. Or, if you do need to pass it around as a string, then use this:

```python
now.strftime("%c")
```
That will provide the locale specific version of the date as a string.
