### ISSUE TITLE
requests module dependency

### ISSUE THREAD

**Issue by riccardoklinger** [riccardoklinger/OSMquery#29]
The tool fails under ArcGIS 10.4.1 with Python 2.7.10. installed as it has unmet dependencies. Maybe switch to more robust method for URL requests like urllib2?

**Comment by riccardoklinger** [comment]
Hi @rastrau I've uploaded a new branch https://github.com/riccardoklinger/OSMquery/tree/requestsreplace for dealing with the requests module issue. this was tested in ArcMAP 10.6.1 and ArcGIS Pro 2.2.2 
It uses the build in urllib / urllib2 modules:
`try:
    # For Python 3.0 and later
    from urllib.request import urlopen
except ImportError:
    # Fall back to Python 2's urllib2
    from urllib2 import urlopen`
So it should work with Py2 and Py3... Will you be able to test this on an older ArcGIS Version?

**Comment by rastrau** [comment]
Very cool, thank you @riccardoklinger! I'll try to get around to testing it using 10.4.1 and 10.5.1 sometime in the next few days (rather: evenings).

**Comment by riccardoklinger** [comment]
tried it in 10.4.1 alrready. works like a charm.
will merge it now.
