### ISSUE TITLE
adding fields fails 

### ISSUE THREAD

**Issue by riccardoklinger** [riccardoklinger/OSMquery#31]
The OSM data structure contains tags with numbers in the name, like "3drtype".
Adding fields for this tag fails as it is not supported in ArcGIS. 
Maybe add an underscore in front?

**Comment by rastrau** [comment]
Good point. I was pondering at some point if there may be other pitfalls than ":", but didn't think of this one. I *think*, ArcGIS default behaviour would be to add "F" (field) though? (like it adds "T" for incompatible FGDB table names) If we can verify this to be default, I suggest sticking to it.

**Comment by riccardoklinger** [comment]
here is an example query for the issue:
[out:json][timeout:60][date:"2018-09-13T13:38:13Z"];(node["building"](53.52386428241717,9.978630156228677,53.53481651233273,10.005297174833016);way["building"](53.52386428241717,9.978630156228677,53.53481651233273,10.005297174833016);relation["building"](53.52386428241717,9.978630156228677,53.53481651233273,10.005297174833016););(._;>;);out;>;

**Comment by riccardoklinger** [comment]
after contacting three persons, I would ussgest to use the underscore addition.
a "3dr:type" would then be: "_3drtype
