### ISSUE TITLE
Provide User-Agent for Overpass API requests

### ISSUE THREAD

**Issue by mmd-osm** [riccardoklinger/OSMquery#34]
Please provide a proper User-Agent in HTTP Header for Overpass API requests, not only the generic one sent by the Python franework. This helps troubleshooting potential issues on the server side.

**Comment by riccardoklinger** [comment]
Will implement this soon. No big deal! Any requirements from your side?

**Comment by mmd-osm** [comment]
Thanks for the quick reply. There are really no hard requirements, like including an email address. It would be helpful though, if the user agent would somehow point to this repo. Just putting in osmquery in your favorite search engine will link to some Mapbox tool, so that wouldn't really useful to contact you.

**Comment by riccardoklinger** [comment]
Issue solved in 01ed8464a376de7ff50c580287cd88359167379e as I added "User-Agent" OSMquery and "Issue-Handler" with a link to this repo as header items. please test and close @mmd-osm

**Comment by mmd-osm** [comment]
Thanks! Can you please put everything in the User-Agent Header instead, as a non-standard header "Issue-Handler" will not show up in the Apache log files.

**Comment by riccardoklinger** [comment]
done User-Agent is now "OSMquery/https://github.com/riccardoklinger/OSMquery"

**Comment by riccardoklinger** [comment]
can i close @mmd-osm ?

**Comment by mmd-osm** [comment]
Great, thanks!
