### ISSUE TITLE
Make date query parameter optional?

### ISSUE THREAD

**Issue by vovchykbratyk** [riccardoklinger/OSMquery#42]
Just an idea, would like to have the DTG optional.  I've been trying to get this working with a disconnected overpass instance set up on a corporate intranet, and there are only periodic imports/updates of the planet.osm content.  What I'd like to see is more of a query that simply shows me what is present in the data holdings at the moment, not limit by date.  Is this possible?  Sorry if this is a dumb question, I am new to the overpass API and it is somewhat complex to work with (compared to a typical Esri feature service).

**Comment by riccardoklinger** [comment]
Is there a way to have access to your infrastructure? 

Von meinem iPhone gesendet

**Comment by vovchykbratyk** [comment]
Unfortunately no, there is no path from it to the internet.  But it is a mirror of OSM that is refreshed periodically.

**Comment by riccardoklinger** [comment]
Hi @vovchykbratyk , ATM I don't have a working license for ArcGIS Desktop. So I can't help you directly. MAybe @rastrau is able to or @michaelmgis . But I am open for a freelancing support contract ;-)

**Comment by rastrau** [comment]
Hi @vovchykbratyk: I just pushed a change to OSMquery which should allow you to empty the datetime parameter field and run your query against your local Overpass instance without requiring specific validity of OSM features.

(The default behavior is still that the current datetime (of opening the tool) is put into the parameter field. I think that covers more use cases by more users.)

Can you please check if this works as intended and addresses your need? I tested on an Esri ArcGIS 10.6 instance against the usual Overpass API endpoint. The tool outputs the query that is sent to your API endpoint for quality assurance.

**Comment by rastrau** [comment]
Hi @vovchykbratyk or anybody else interested: Have you had an opportunity to test this? Did the fix work for you?
