### ISSUE TITLE
Problem applying  OSMquery

### ISSUE THREAD

**Issue by FrancisW1** [riccardoklinger/OSMquery#44]
Hey,

I'm rather new to using ArcGIS. So maybe there is a very simple solution to my problem. 
When I start OSMquery I receive an error warning.
Can someone explain my mistake and help me solve my problem?
![Bild](https://user-images.githubusercontent.com/92447054/137150607-c9fe1c98-d6a5-4404-a4f9-b4844d61fd28.png)

**Comment by rastrau** [comment]
It seems to me that you may not have rights to create feature classes in `arcpy.env.scratchWorkspace`. 

1) To what path does your Scratch Workspace point? 
2) Does that path exist? 
3) Do you have write access at that location?

**Comment by FrancisW1** [comment]
Thank you very kindly. Yes indeed it seems I have a problem concerning my license.

**Comment by FrancisW1** [comment]
I solved my license issue. The Tool works perfectly and I like it. 
Thanks for the great Tool and your support.

**Comment by rastrau** [comment]
Good to hear. The tool's been initiated by @riccardoklinger 👍. 
Thank you!
