### ISSUE TITLE
enable direct query editing

### ISSUE THREAD

**Issue by riccardoklinger** [riccardoklinger/OSMquery#8]
Currently the queries are generated in the pythoncode. I would love to enable the user to change or even define the query by themselves in the toolbox

**Comment by rastrau** [comment]
I think this is a candidate for a second tool in the toolbox, an expert tool with Overpass compatible free-form queries.

**Comment by riccardoklinger** [comment]
I created the OverpassQuery branch for this.
@rastrau @michaelmgis please test and provide feedback. looks good to me, so I am ready for merge. commits from customCRS branch should be merged first!

**Comment by riccardoklinger** [comment]
done in new tool in commit a3a076ba6a930e0307f3aab5b761199c068b6ba5
