### ISSUE TITLE
Get all data of a key without definition of a tag

### ISSUE THREAD

**Issue by michaelmgis** [riccardoklinger/OSMquery#9]
Get all data of a key without definition of a tag.

Example: highway=*

**Comment by riccardoklinger** [comment]
This is already feasible using the multiple select option from @rastrau in 6252a88fe56465bc611786a508d167fb0c815b49

**Comment by riccardoklinger** [comment]
please test and close?!

**Comment by riccardoklinger** [comment]
@rastrau : can we add an asterix to the config list and select all?

**Comment by riccardoklinger** [comment]
I'll take care of it.

**Comment by riccardoklinger** [comment]
fixed in 5d67efb22b07e0ec8d186ea85309c7630a57e038 .. @michaelmgis please test and close.
